### ISSUE TITLE
Custom S3 - DreamObjects s3 Not working

### ISSUE THREAD

**Issue by bcordis** [akeeba/plg_filesystem_s3#11] opened 2024-03-25 15:18 UTC
### Steps to reproduce the issue
Using the Custom S3 options
Using the Secret Key provided by DreamObjects will fail to validate

### Expected result
Able to save server with appropriate Secret Key

### Actual result
Save will error out stating Secret Key is invalid

### Troubleshooting already performed
Try setting up different src->Rule->SecretKeyRule.php $regex to allow the key to work.

### System information

* **Joomla! version**: 5.1.0-beta2
* **Joomla! backend template**: Atum
* **Joomla! frontend template**: Cassiopeia
* **PHP version**: 8.3.0
* **Browser (name and version)**: Chrome 123.0.6312.59 (Official Build) (x86_64)

**Comment by nikosdion** [comment] 2024-03-25 16:28
The problem is that DreamHost **IS NOT** compatible with Amazon S3. At all. Amazon S3 publishes the regex for checking access and secret keys for validity. DreamHost doesn't give a crap. They do something entirely different.

The only thing possible here is to remove this check altogether.

It's not a bug, it's accommodating a **broken third party service provider**. Closing as it's already been fixed.

**Closed as completed by nikosdion** 2024-03-25 16:28 UTC
